port=8000

doppler_token="env:$DOPPLER_TOKEN"

[postgres]
db_password="env:$DB_PASSWORD"
db_port="env:$DB_PORT"
db_user="env:$DB_USER"
db_host="env:$DB_HOST"
db_name="env:$DB_NAME"

[bert]
model="DeepPavlov/rubert-base-cased"
skills_model_path="Delicalib/ru_skill_labels"

[roberta]
model="FacebookAI/xlm-roberta-large"

[openai]
gpt_token="env:$GPT_API_KEY"